Import('*')

test_env = env.Clone()
test_env.Append(CPPPATH = '#/thirdparty/Catch2/single_include')

conf = Configure(test_env)
if not conf.CheckCXXHeader('catch2/catch.hpp'):
    print('Catch test framework not found! Get it with:\n\n'
          '  git submodule init\n'
          '  git submodule update\n')
    Exit(1)
test_env = conf.Finish()

test_env.Program('tests', Glob('*.cpp'), LIBS=[rts, util])
